[tools]
ruby = 'latest'
nodejs = 'lts'
python = "latest"
neovim = 'latest'
postgres = "latest"
zoxide = 'latest'
pnpm = 'latest'
lazydocker = 'latest'
go = 'latest'
tmux = "latest"

[alias]
lazydocker = 'https://github.com/comdotlinux/asdf-lazydocker'

[settings]
experimental = true
