[tools]
ruby = 'latest'
nodejs = 'lts'
python = "latest"
neovim = 'latest'
postgres = '15'
zoxide = 'latest'
pnpm = 'latest'
lazydocker = 'latest'
tmux = 'latest'
zellij = 'latest'
go = 'latest'

[plugins]
lazydocker = 'https://github.com/comdotlinux/asdf-lazydocker'

[settings]
experimental = true
