[tools]
ruby = "3.4.4"
nodejs = 'lts'
python = "3.11"
neovim = "latest"
postgres = "latest"
zoxide = 'latest'
pnpm = 'latest'
lazydocker = 'latest'
go = 'latest'
tmux = "latest"
github-cli = "latest"
starship = "latest"
fzf = "latest"
node = "latest"
ripgrep = "latest"
fd = "latest"
lazygit = "latest"
flyctl = "latest"
yazi = "latest"
bun = "latest"

[alias]
lazydocker = 'https://github.com/comdotlinux/asdf-lazydocker'

[settings]
experimental = true
