[tools]
ruby = '3.2.2'
nodejs = 'lts'
python = '3.10.5'
neovim = 'latest'
fzf = '0.30.0'
postgres = '12.5'
zoxide = '0.8.2'
pnpm = '8.5.0'
lazydocker = 'latest'
tmux = 'latest'
zellij = 'latest'

[plugins]
lazydocker = 'https://github.com/comdotlinux/asdf-lazydocker'
